server:
    port: ${SERVER_PORT}
spring:
    datasource:
        url: ${DB_URL}
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        driverClassName: ${DB_DRIVER}
    jpa:
        hibernate:
            ddl-auto: update
        database-platform: ${DB_PLATFORM}
security:
    allowed-endpoints: ${ALLOWED_ENDPOINTS}
